import lex

tokens = [ 'COMANDO_INICIAR','COMANDO_FINALIZAR','COMANDO_AVANZAR','COMANDO_GIRAR_IZQ','COMANDO_COGER_ZUMBADOR', 'COMANDO_DEJAR_ZUMBADOR', 'COMANDO_APAGAR','SENTENCIA_DEFINE_NUEVA_INSTRUCCION','SENTENCIA_COMO','SENTENCIA_SI','SENTENCIA_ENTONCES','SENTENCIA_SINO','SENTENCIA_REPETIR','SENTENCIA_REPETIR_VECES','SENTENCIA_MIENTRAS','SENTENCIA_MIENTRAS_HACER','OPERADOR_Y','OPERADOR_O','OPERADOR_NO','CONDICION_FRENTE-LIBRE','CONDICION_JUNTO-A-ZUMBADOR','CONDICION_ORIENTADO-AL-ESTE','CONDICION_FRENTE-BLOQUEADO','CONDICION_NO-JUNTO-A-ZUMBADOR','CONDICION_ORIENTADO-AL-OESTE','CONDICION_IZQUIERDA-LIBRE','CONDICION_ALGUN-ZUMBADOR-EN-LA-MOCHILA','CONDICION_NO-ORIENTADO-AL-NORTE','CONDICION_IZQUIERDA-BLOQUEADA','CONDICION_NINGUN-ZUMBADOR-EN-LA-MOCHILA','CONDICION_NO-ORIENTADO-AL-SUR','CONDICION_DERECHA-LIBRE','CONDICION_ORIENTADO-AL-NORTE','CONDICION_NO-ORIENTADO-AL-ESTE','CONDICION_DERECHA-BLOQUEADA','CONDICION_ORIENTADO-AL-SUR','CONDICION_NO-ORIENTADO-AL-OESTE','BOOLEANO_VERDADERO','BOOLEANO_FALSO']
t_COMANDO_INICIAR = 'iniciar-'
t_COMANDO_FINALIZAR = 'finalizar-'
t_COMANDO_AVANZAR = 'avanza'
t_COMANDO_GIRAR_IZQ = 'gira-izquierda'
t_COMANDO_COGER_ZUMBADOR = 'coge-zumbador'
t_COMANDO_DEJAR_ZUMBADOR = 'deja-zumbador'
t_COMANDO_APAGAR = 'apagate'
t_SENTENCIA_DEFINE_NUEVA_INSTRUCCION = 'define-nueva-instrucion'
t_SENTENCIA_COMO = 'como'
t_SENTENCIA_SI = 'si'
t_SENTENCIA_ENTONCES = 'entonces'
t_SENTENCIA_SINO = 'sino'
t_SENTENCIA_REPETIR = 'repetir'
t_SENTENCIA_REPETIR_VECES = 'veces'
t_SENTENCIA_MIENTRAS = 'mientras'
t_SENTENCIA_MIENTRAS_HACER = 'hacer'
t_OPERADOR_Y = 'y'
t_OPERADOR_O = 'o'
t_OPERADOR_NO = 'no'




def t_NUMBER(t):
    r'\d+'
    t.value = int(t.value)
    return t

# Error handling rule
def t_error(t):
    print("Illegal character '%s'" % t.value[0])
    t.lexer.skip(1)

lex.lex() # Build the lexer

lex.input("avanza")
while True:
    tok = lex.token()
    if not tok: break
    print (str(tok.value) + " - " + str(tok.type))
